### ISSUE TITLE
New UI and Home Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/doc2pen#136]
We wish to have a new UI for the home page since the current one is not visually appealing and the code base is quite messed up

# Certain Guidelines:
- All commits are to be made in the ```beta_1``` branch
- Inline CSS and Internal CSS is not permitted
- You can use Bootstrap or Materialize or Tailwind ( But do not use more than one framework)
- All assets (i.e. images, illustrations,etc) are to be stored inside an ```assets/images/``` directory of the ```beta_1``` branch
- You are expected to name the assets properly. Something like ```xybfg_grh1tgn_pic.png``` is not expected
- Every Pull Request is expected to contain:
      - A relevant title
      - Screenshots of the changes/enhancements/bug fixes 
      - Written Description of what you have done
      ** Additionally your code is expected to be documented with comments
       (GIFs for fun are welcome)
- Please complete the part of the page you have taken and then only move to the next one
- For repeatable elements in the page, let's say cards, something like insertion using JSON will be a great thing
- Do not forget to optimize the assets
- Since this is going to be a single page website (excluding our editor page), so all the CSS should be inside a ```style.css``` file and the HTML code inside the ```index.html``` file of the ```beta_1``` branch
- Use only __Montserrat Font__

# A Rough Sketch of what we are looking at
![Doc2Pen_Pencil_UI](https://user-images.githubusercontent.com/46641503/92564115-48e1df80-f296-11ea-9d44-1ab1017faf6b.png)
![Doc2Pen_Pencil_UI_2](https://user-images.githubusercontent.com/46641503/92564126-4bdcd000-f296-11ea-98b1-5ea0b405af22.png)

# Tasks that are required to be done:
- [x] Ensure Mobile Responsiveness ( Please do not claim this, it is expected as a part of your PRs, if there's an issue with some part of the website you can directly give a PR to fix it)
- [x] Navigation Bar ( For now please keep in mind we are working on a __light theme__)
- [ ] Home Section
- [x] About Section ( I expect you to be creative here and add things beyond what I have given in the sketches)
- [x] Team Section
- [x] Contact Section
- [x] Footer ( This is the simplest one, nothing fancy required here)
- Please ensure the color theme is consistent throughout the page and work with the mentors on the same
- [ ] Additional tasks ( Can  be done in parallel or after the above are done):
           -  [ ] Search Engine Optimization ( One single PR with all relevant meta tags including og is expected. Do not forget to elaborate about the same on the description of your PR)  __Use GTMetrics/LightHouse to check performance__
           - Website Optimization ( Code/Assets/Load Time)
           - Improved Animations
           - Improved Documentation

**Comment by himanshujaidka** [comment]
assign some task to me

**Comment by sameersrivastava13** [comment]
Can i work on the footer part? If yes, please assign the sub task to me.

**Comment by raksha009** [comment]
I would like to work on navigation bar.

**Comment by Adyasha8105** [comment]
Can I work on navbar?

**Comment by himanshujaidka** [comment]
assign team page to me

**Comment by himanshujaidka** [comment]
assign equal work to all interested contributors

**Comment by smaranjitghose** [comment]
> Can I work on navbar? And also team section @smaranjitghose

Go ahead with the Navigation Bar please

**Comment by smaranjitghose** [comment]
> Can i work on the footer part? If yes, please assign the sub task to me.

Sure, go ahead with the footer, please. The content is fairly simple. Try to come up with a good design

**Comment by smaranjitghose** [comment]
> assign team page to me

Sure, go ahead with the team "section"( Do not make a separate page, remember it is supposed to be a single page website)

**Comment by himanshujaidka** [comment]
ok @smaranjitghose

**Comment by smaranjitghose** [comment]
> I would like to work on navigation bar.
@raksha009 Can you please have a look at the other sub tasks and claim something you would like other than the ones already assigned

**Comment by himanshujaidka** [comment]
and I would also interested to make contact form @smaranjitghose

**Comment by smaranjitghose** [comment]
@Adyasha8105 @sameersrivastava13 @himanshujaidka Please understand this is meant to be a collaborative effort. So if @Adyasha8105 is making the NavBar, the UI should go well with @himanshujaidka team section and @sameersrivastava13 's footer. Work with mentors if you help with deciding the UI (including color schemes, gradients, etc). I have given a basic layout, so now I expect to see your work. Feel free to contact @anushbhatia for UI related help as well

Tentative Deadlines (for first PR related to the task you have been assigned):
@Adyasha8105 : 2 days
@sameersrivastava13 : 2 days
@himanshujaidka : 4 days

Keep in mind, your first PR is not supposed to be the best but a starting point for meeting the requirements, so do not wait until 1 week or 10 days to show your work. Keep pushing your commits and getting feedback

If I am not available to review, get in touch with @anushbhatia. Otherwise, we have many mentors for this, request them to give you feedback

**Comment by smaranjitghose** [comment]
> and I would also interested to make contact form @smaranjitghose

One section at a time, please😊. After the team section is done and if it's available (or you can improve it), definitely I will assign you.

**Comment by raksha009** [comment]
> > I would like to work on navigation bar.
> > @raksha009 Can you please have a look at the other sub tasks and claim something you would like other than the ones already assigned

What about home section 😅. In home section, we have to use the same illustration which is already there!?

**Comment by smaranjitghose** [comment]
> > > I would like to work on navigation bar.
> > > @raksha009 Can you please have a look at the other sub tasks and claim something you would like other than the ones already assigned
> 
> What about home section 😅. In home section, we have to use the same illustration which is already there!?

Actually not, the current illustration doesn't make much sense to the essence of this project. So I would expect you to come up with something different

**Comment by smaranjitghose** [comment]
@sameersrivastava13 Are you giving a PR today for the footer?

**Comment by sameersrivastava13** [comment]
> @sameersrivastava13 Are you giving a PR today for the footer?
> @himanshujaidka 2 more days for you
> @Adyasha8105 Good Job!. Do you wish to take the contact form section?

@smaranjitghose i can add a simple footer instantly. But to add the same wave like footer it will take some time actually.

**Comment by smaranjitghose** [comment]
> > @sameersrivastava13 Are you giving a PR today for the footer?
> > @himanshujaidka 2 more days for you
> > @Adyasha8105 Good Job!. Do you wish to take the contact form section?
> 
> @smaranjitghose i can add a simple footer instantly. But to add the same wave like footer it will take some time actually.

Okay take some more time

**Comment by himanshujaidka** [comment]
@smaranjitghose please give me more time I was unable to do work due to some personal reason, from today I have started the work

**Comment by smaranjitghose** [comment]
> @smaranjitghose please give me more time I was unable to do work due to some personal reason, from today I have started the work

Sure, then by this Tuesday can I have a PR from you?

**Comment by Adyasha8105** [comment]
> @sameersrivastava13 Are you giving a PR today for the footer?
> @himanshujaidka 2 more days for you
> @Adyasha8105 Good Job!. Do you wish to take the contact form section?

@smaranjitghose Ya sure :) I will work on the contact page.

**Comment by smaranjitghose** [comment]
> > @sameersrivastava13 Are you giving a PR today for the footer?
> > @himanshujaidka 2 more days for you
> > @Adyasha8105 Good Job!. Do you wish to take the contact form section?
> 
> @smaranjitghose Ya sure :) I will work on the contact page.

It's fairly a small section, so can I expect a PR by 17th or before for this?

**Comment by AyuSoni25** [comment]
Hello @smaranjitghose and @anushbhatia ,
I would like to work on the About section, please assign me that task.

**Comment by smaranjitghose** [comment]
> Hello @smaranjitghose and @anushbhatia ,
> I would like to work on the About section, please assign me that task.

Can you give a PR for it by this weekend?

**Comment by Adyasha8105** [comment]
@smaranjitghose Can I take the team section?

**Comment by himanshujaidka** [comment]
@smaranjitghose tomorrow I'll give pr
almost work is done

**Comment by smaranjitghose** [comment]
> @smaranjitghose tomorrow I'll give pr
> almost work is done

Okay, after your PR @Adyasha8105 will work on improvements

**Comment by AyuSoni25** [comment]
> > Hello @smaranjitghose and @anushbhatia ,
> > I would like to work on the About section, please assign me that task.
> 
> Can you give a PR for it by this weekend?

I can do it by this Monday (21/09/2020)

**Comment by prathyushalahari** [comment]
@smaranjitghose is there anything left to work on?

**Comment by smaranjitghose** [comment]
> > > Hello @smaranjitghose and @anushbhatia ,
> > > I would like to work on the About section, please assign me that task.
> > 
> > 
> > Can you give a PR for it by this weekend?
> 
> I can do it by this Monday (21/09/2020)

Awesome then! Looking forward to your PR. Use the slack channel for getting feedback and sharing any issues you face

**Comment by smaranjitghose** [comment]
> @smaranjitghose is there anything left to work on?

There's a lot left in the other issue. Do check that out, please

 For this one, you can work on:
- Enhancements to the existing Contact, Footer Section if you feel anything needs to be done
- SEO is left out completely
- Integrating Formspree with the Contact Form

BTW, are you well versed with React or NextJS?

**Comment by prathyushalahari** [comment]
Ok Sure I will work on next issue and I am not Versed on React

**Comment by AyuSoni25** [comment]
Hello@smaranjitghose,
I would like to contribute to the home section as well, if it has not been assigned to anybody else.

**Comment by smaranjitghose** [comment]
> Hello@smaranjitghose,
> I would like to contribute to the home section as well, if it has not been assigned to anybody else.

Sure, you can continue once you have fixed the errors with you are having with your branch

**Comment by ritvij14** [comment]
@smaranjitghose I looked at all the comments but I am a bit confused with what is assigned and what isn't :sweat_smile:. Could you please tell if there is some work left to be done?

Also, from the issue description, what framework are we using? I am good at Bootstrap and Tailwind. If Materialize is needed I will learn it. And I have worked with React as well (but not Next :sweat_smile:)

**Comment by imsahil007** [comment]
> @smaranjitghose I looked at all the comments but I am a bit confused with what is assigned and what isn't . Could you please tell if there is some work left to be done?
> 
> Also, from the issue description, what framework are we using? I am good at Bootstrap and Tailwind. If Materialize is needed I will learn it. And I have worked with React as well (but not Next )

You can work on the mobile responsiveness of the website. I think that should be a continuous process and we shouldn't leave it for the end.
Home section is also a choice.

**Comment by smaranjitghose** [comment]
> @smaranjitghose I looked at all the comments but I am a bit confused with what is assigned and what isn't 😅. Could you please tell if there is some work left to be done?
> 
> Also, from the issue description, what framework are we using? I am good at Bootstrap and Tailwind. If Materialize is needed I will learn it. And I have worked with React as well (but not Next 😅)

Bootstrap
